import React from 'react';
import Head from 'next/head';

import { Pin, Username, WaitingRoom } from 'components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hey, what's up!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Pin />
        <Username />
        <WaitingRoom />
      </div>
    </div>
  );
}
